ralexstokes/ethereum-consensus

- examples/bls.rs
- src/crypto.rs
> Enhance crypto APIs

- src/phase0/state_transition/mod.rs
Fixes https://github.com/ralexstokes/ethereum_consensus/issues/68
> return error in compute_shuffled_index

- src/crypto.rs
- src/serde.rs
> avoid panic on invalid input when serde on hex

- src/builder/mod.rs
- src/domains.rs
following https://github.com/ethereum/builder-specs/pull/15
> add `DOMAIN_APPLICATION_BUILDER` for builder specs

- Cargo.toml
- src/altair/presets/mainnet.rs
- src/altair/sync.rs
- src/altair/validator.rs
- src/clock.rs
- src/lib.rs
- src/networking.rs
- src/phase0/operations.rs
- src/phase0/presets/mainnet.rs
- src/phase0/state_transition/block_processing.rs
- src/phase0/state_transition/mod.rs
- src/phase0/validator.rs
> Add consensus clock

- tests/spec_test_runners/bls/mod.rs
Addresses item 1 of #113 
BLS tests with the new test runner format.
> Phase 0 bls tests

- src/altair/block_processing.rs
- src/altair/epoch_processing.rs
- src/altair/helpers.rs
- src/altair/state_transition/block_processing.rs
- src/altair/state_transition/epoch_processing.rs
- src/altair/state_transition/helpers.rs
- src/bellatrix/epoch_processing.rs
- src/bellatrix/helpers.rs
- src/bellatrix/state_transition/block_processing.rs
- src/bellatrix/state_transition/epoch_processing.rs
- src/bellatrix/state_transition/helpers.rs
- src/bellatrix/state_transition/mod.rs
- src/bin/gen_spec.rs
- src/phase0/block_processing.rs
- src/phase0/epoch_processing.rs
- src/phase0/helpers.rs
- src/state_transition/context.rs
- src/state_transition/error.rs
- tests/spec_test_runners/operations/mod.rs
> More operations

- Cargo.toml
- src/networking.rs
implements `fmt::Display` on `PeerId`
> impl display for PeerId

- src/altair/state_transition/block_processing.rs
- src/bellatrix/state_transition/block_processing.rs
- src/phase0/block_processing.rs
- src/state_transition/error.rs
Addresses https://github.com/ralexstokes/ethereum-consensus/pull/167#discussion_r1080741005
> Correct typo in InvalidVoluntaryExit variant

- Cargo.toml
- src/configs/goerli.rs
- src/configs/mainnet.rs
- src/configs/minimal.rs
- src/configs/mod.rs
- src/configs/sepolia.rs
- src/state_transition/context.rs
- src/state_transition/error.rs
- supports loading a `Context` from a file
- exposes the consensus clock from the `Context`
> updates for custom networks

- src/clock.rs
> fix possible underflow on clock arithmetic

- ethereum-consensus/src/clock.rs
- ethereum-consensus/src/configs/holesky.rs
- ethereum-consensus/src/configs/mod.rs
- ethereum-consensus/src/state_transition/context.rs
> feat: support holesky

- ethereum-consensus/src/clock.rs
* fix underflow in `duration_until_slot`
* migrate clock to `ns` precision
> enhance `Clock`

- ethereum-consensus/src/altair/genesis.rs
- ethereum-consensus/src/altair/spec/mod.rs
- ethereum-consensus/src/bellatrix/genesis.rs
- ethereum-consensus/src/bellatrix/spec/mod.rs
- ethereum-consensus/src/phase0/genesis.rs
- spec-gen/src/generator.rs
- spec-gen/src/visitors.rs
let's us drop some code in later phases by also specializing return types
> Spec gen for return types

- .github/workflows/ci.yml
- ethereum-consensus/src/bin/ec/validator/keys.rs
- justfile
> derive validator keys following EIP-2334

- ethereum-consensus/Cargo.toml
- ethereum-consensus/src/bin/ec/validator/keys.rs
- ethereum-consensus/src/bin/ec/validator/keystores.rs
- ethereum-consensus/src/bin/ec/validator/mnemonic.rs
- ethereum-consensus/src/bin/ec/validator/mod.rs
- ethereum-consensus/src/crypto.rs
> generate keystores

- ethereum-consensus/src/capella/spec/mod.rs
- ethereum-consensus/src/deneb/spec/mod.rs
some missing spec updates after the last capella impls
> generate spec after latest updates for capella

- ethereum-consensus/Cargo.toml
- ethereum-consensus/src/bellatrix/block_processing.rs
- ethereum-consensus/src/bellatrix/execution_payload.rs
- ethereum-consensus/src/bellatrix/fork_choice.rs
- ethereum-consensus/src/capella/block_processing.rs
- ethereum-consensus/src/capella/execution_payload.rs
- ethereum-consensus/src/capella/fork.rs
- ethereum-consensus/src/configs/goerli.rs
- ethereum-consensus/src/configs/holesky.rs
- ethereum-consensus/src/configs/mainnet.rs
- ethereum-consensus/src/configs/minimal.rs
- ethereum-consensus/src/configs/sepolia.rs
- ethereum-consensus/src/crypto.rs
- ethereum-consensus/src/deneb/block_processing.rs
- ethereum-consensus/src/deneb/execution_payload.rs
- ethereum-consensus/src/deneb/fork.rs
- ethereum-consensus/src/serde.rs
- ethereum-consensus/src/state_transition/context.rs
> update to latest ssz-rs

- beacon-api-client/Cargo.toml
- beacon-api-client/examples/get_block.rs
- beacon-api-client/src/api_client.rs
- beacon-api-client/src/types.rs
fixes #309 
the assumptions for the API client params broke after #292 
thanks @Doozers for pointing it out!
> use correct stringification logic after type updates

- ethereum-consensus/src/deneb/blob_sidecar.rs
- ethereum-consensus/src/deneb/spec/mod.rs
cf: https://github.com/ethereum/consensus-specs/pull/3534
> remove `BLOB_TX_TYPE` from spec

- beacon-api-client/src/types.rs
helpful derives while working with the crates :)
> feat: enable default traits for validator types 

- ethereum-consensus/Cargo.toml
a bit more functionality for generalized indices
> updates ssz-rs dep

- ethereum-consensus/Cargo.toml
- ethereum-consensus/src/altair/spec/mod.rs
- ethereum-consensus/src/bellatrix/spec/mod.rs
- ethereum-consensus/src/capella/spec/mod.rs
- ethereum-consensus/src/deneb/spec/mod.rs
- ethereum-consensus/src/phase0/helpers.rs
- ethereum-consensus/src/phase0/spec/mod.rs
- ethereum-consensus/src/primitives.rs
- spec-tests/runners/shuffling.rs
around 30% speed up running across some spec tests
> implement optimized index shuffling and add support in spec tests

- ethereum-consensus/src/altair/light_client.rs
- ethereum-consensus/src/altair/presets/mainnet.rs
- ethereum-consensus/src/altair/presets/minimal.rs
- ethereum-consensus/src/altair/spec/mod.rs
- ethereum-consensus/src/bellatrix/presets/mainnet.rs
- ethereum-consensus/src/bellatrix/presets/minimal.rs
- ethereum-consensus/src/bellatrix/spec/mod.rs
- ethereum-consensus/src/capella/light_client.rs
- ethereum-consensus/src/capella/mod.rs
- ethereum-consensus/src/capella/presets/mainnet.rs
- ethereum-consensus/src/capella/presets/minimal.rs
- ethereum-consensus/src/capella/spec/mod.rs
- ethereum-consensus/src/deneb/light_client.rs
- ethereum-consensus/src/deneb/mod.rs
- ethereum-consensus/src/deneb/presets/mainnet.rs
- ethereum-consensus/src/deneb/presets/minimal.rs
- ethereum-consensus/src/deneb/spec/mod.rs
- spec-gen/src/generator.rs
- spec-tests/runners/ssz_static.rs
- spec-tests/test_meta.rs
> Add latest light client types and implement spec tests for them

- ethereum-consensus/src/altair/spec/mod.rs
- ethereum-consensus/src/bellatrix/spec/mod.rs
- ethereum-consensus/src/capella/spec/mod.rs
- ethereum-consensus/src/deneb/spec/mod.rs
- ethereum-consensus/src/phase0/helpers.rs
- ethereum-consensus/src/phase0/spec/mod.rs
> implement optimized shuffling for proposer computation

- .github/workflows/ci.yml
- Cargo.toml
- justfile
- spec-gen/src/generator.rs
- spec-tests/runners/epoch_processing.rs
- spec-tests/runners/operations.rs
- spec-tests/runners/rewards.rs
- spec-tests/runners/shuffling.rs
- spec-tests/runners/utils.rs
- spec-tests/test_utils.rs
> ensure we are running all CI jobs on entire repo

- Cargo.toml
- ethereum-consensus/src/altair/sync.rs
- ethereum-consensus/src/bellatrix/state_transition.rs
- ethereum-consensus/src/capella/bls_to_execution_change.rs
- ethereum-consensus/src/capella/withdrawal.rs
- ethereum-consensus/src/crypto.rs
- ethereum-consensus/src/deneb/beacon_block.rs
- ethereum-consensus/src/deneb/blob_sidecar.rs
- ethereum-consensus/src/deneb/execution_payload.rs
- ethereum-consensus/src/deneb/spec/mod.rs
- ethereum-consensus/src/phase0/beacon_block.rs
- ethereum-consensus/src/phase0/operations.rs
- ethereum-consensus/src/signing.rs
- ethereum-consensus/src/ssz/byte_list.rs
- ethereum-consensus/src/ssz/byte_vector.rs
- ethereum-consensus/src/types/beacon_block.rs
- ethereum-consensus/src/types/beacon_block_body.rs
- ethereum-consensus/src/types/beacon_state.rs
- ethereum-consensus/src/types/blinded_beacon_block.rs
- ethereum-consensus/src/types/blinded_beacon_block_body.rs
- ethereum-consensus/src/types/execution_payload.rs
- ethereum-consensus/src/types/execution_payload_header.rs
- spec-gen/src/type_generator.rs
- spec-tests/runners/merkle_proof.rs
> update to latest ssz-rs crate with proving capability

- ethereum-consensus/src/fork.rs
- ethereum-consensus/src/state_transition/context.rs
add `Fork::Electra` variant to `Fork` enum.
> feat: add electra variant to fork enum

- ethereum-consensus/src/crypto/bls.rs
> directly support EIP-2333 for BLS secret keys
