ralexstokes/ethereum-consensus

- examples/sketch.rs
- src/phase0/presets/mainnet.rs
- src/phase0/presets/minimal.rs
- src/phase0/presets/mod.rs
- src/phase0/state_transition/context.rs
- src/phase0/state_transition/mod.rs
We will need some sort of `Context` for a variety of state transition optimization we will want, and this also is a nice place to pass around some configuration data that is a bit unwieldy to pass around in other ways (e.g. thru compile-time constants)
> Add state transition context

- src/primitives.rs
there are several places in the state transition (e.g. see #26) where we compare `Bytes32` to a `Root` type.
to improve the ergonomics of state transition, we define a `PartialEq` instance here
> define `PartialEq` for `Bytes32` and `Root` types

- src/crypto.rs
- src/phase0/state_transition/context.rs
- src/phase0/state_transition/genesis.rs
- src/phase0/state_transition/mod.rs
main thing is to drop the `MerkleizationContext` which is now just static data at the global scope.
this PR also integrates some minor API changes for the List and Vector types that lay the ground-work for a broader effort in the `ssz_rs` repo to add hashing caching (and multiproofs eventually).
> integrate recent ssz changes

- src/phase0/state_transition/block_processing.rs
i was a bit too hasty when making the skeletons of the various subtransitions and copypasta'd some `mut` `BeaconBlock`s into the code.
there is no reason to mutate a beacon block in the state transition so let's drop the `mut` capability
> fix mutability on `BeaconBlock` type in `block_processing`

- src/phase0/state_transition/epoch_processing.rs
Not sure if the usage of `clone()` is desired but had to get rid of the borrow...not sure if there's a more Rust way
Also lmk if I should keep the PR's specific to a fn, or if I should group them together in a PR so that I'm not spamming with PRs consisting of a few lines of code.
> feat: add fn body for 'process_randao_mixes_reset'

- src/phase0/state_transition/epoch_processing.rs
@ralexstokes before I merge this -- since you were just creating skeletons, should I remove `_context` from the fn parameters if it's unused? Or, are you trying to keep everything sorta consistent with `state` and `context` always being passed?
> feat: add fn body for 'process_participation_record_updates'

- src/phase0/state_transition/epoch_processing.rs
- src/phase0/state_transition/mod.rs
This PR is a WIP as I'm having some issues with Rust and am looking for feedback.
I'm trying to implement [`process_registry_updates`](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#registry-updates), which has 3 primary steps:
I think I have the first step completed (obviously open to feedback), but I've had issues on the next step while trying to recreate python's lambda & sorting. This is what I've tried to do:
1. Get validators from state
2. Create an iterator and enumerate over the values to get a tuple of `(ValidatorIndex, &Validator)`
3. Sort the values in place (I think this is what `sort_by` does) with priority of `activation_eligibility_epoch`, then validator's `index` (where the variables in the closure could be removed but are created for …
> feat: add fn body to `process_registry_updates`

- src/phase0/state_transition/epoch_processing.rs
some epoch processing functions returned `Result`s when there was no possibility for `Err`
this PR cleans that up by removing the unnecessary `Result`s
> cleanup unnecessary return values

- src/phase0/mod.rs
- src/phase0/state_transition/epoch_processing.rs
- src/phase0/state_transition/mod.rs
Add skeletons for all remaining functions yet to be implemented but required by `process_rewards_and_penalties` and its related helpers/subfunctions (where duplicate fns are listed here to define their missing dependencies):
- `process_rewards_and_penalties`
- `get_attestation_deltas`
- `get_attestation_component_deltas`
- `get_unslashed_attesting_indices`
- `get_eligible_validator_indices`
- `is_in_inactivity_leak`
- `get_finality_delay`
- `get_base_reward`
- `get_source_deltas`
- `get_target_deltas`
- `get_head_deltas`
- `get_matching_head_attestations`
- `get_inclusion_delay_deltas`
- `get_unslashed_attesting_indices`
- `get_proposer_reward`
- `get_base_reward`
- `get_proposer_reward`
- `get_inactivity_penalty_deltas`
- `is_in_inactivity_leak`
- `get_finality_delay`
- …
> feat: add `process_rewards_and_penalties` impl & helper fns

- src/phase0/state_transition/mod.rs
As part of commit https://github.com/ralexstokes/ethereum_consensus/commit/850c8a01c209a66e63e69e5c2098e65fc0c56a3a, the `InvalidAttestation` and corresponding `error` macro were accidentally included. However, they were deemed unneeded and should not be part of this commit.
> fix: remove `InvalidAttestation` from `Error`

- src/phase0/state_transition/mod.rs
According to spec, `index` should be less than `index_count`. But `None` is returned if so.
```python3
def compute_shuffled_index(index: uint64, index_count: uint64, seed: Bytes32) -> uint64:
assert index < index_count
```
> Fix `index` check in `compute_shuffled_index`

- src/phase0/state_transition/mod.rs
Closes https://github.com/ralexstokes/ethereum_consensus/issues/67
The `epoch` variable was overridden with the epoch for getting randao mix.
According to the spec, this shouldn't happen:
```python3
def get_seed(state: BeaconState, epoch: Epoch, domain_type: DomainType) -> Bytes32:
"""
Return the seed at ``epoch``.
"""
mix = get_randao_mix(state, Epoch(epoch + EPOCHS_PER_HISTORICAL_VECTOR - MIN_SEED_LOOKAHEAD - 1))  # Avoid underflow
return hash(domain_type + uint_to_bytes(epoch) + mix)
```
> Fix `get_seed` fn

- Cargo.toml
- src/networking.rs
In Lighthouse we're adding `mev-rs` as a dependency, and bringing in `ethereum-consensus` is currently adding a duplicate version of `libp2p-core` that's different from upstream.
It seems that `mev-rs` doesn't need `PeerId`, so I've turned this feature _off_ by default. If you'd like a feature name other than `peer-id` let me know (maybe `libp2p`?).
> put libp2p-core behind a feature

- Cargo.toml
avoid dependency issues by pinning otherwise free-floating dep versions
> pin the version of `ssz-rs` in use

- src/primitives.rs
adds `serde::as_string` to the slot field in the Coordinate struct to enable deserializing from json.
> + `serde::as_string` to `Coordinate.slot`

- src/ssz/byte_list.rs
- src/ssz/byte_vector.rs
doing some review of usage of bytes types and code org across this repo and `ssz-rs` and found a few minor cleanups
> clean up ssz byte type formatting

- Cargo.toml
- src/altair/block_processing.rs
- src/altair/state_transition/block_processing.rs
- src/altair/state_transition/helpers.rs
- src/bellatrix/state_transition/block_processing.rs
- src/bellatrix/state_transition/helpers.rs
- src/phase0/block_processing.rs
- src/phase0/helpers.rs
- src/serde.rs
- src/signing.rs
drop unnecessary refs in type sig
update to latest `ssz-rs`
> some updates

- src/phase0/helpers.rs
the sorted check also accounts for duplicates because the comparator is a strict inequality.
changes:
* check for both sorted and non-duplicate properties in a single pass
* if the list is unsorted, then short-circuit and return `AttestingIndicesNotSorted`
* if the list is (weakly) sorted but contains a duplicate, then return `DuplicateIndices` with a single element for each duplicated index
examples and expected behavior:
1. `[0, 1, 2]`: `Ok(())`
2. `[0, 2, 1]`: `Err(AttestingIndicesNotSorted)`
3. `[0, 1, 1]`: `Err(DuplicateIndices([1]))`
4. `[0, 1, 0]`: `Err(AttestingIndicesNotSorted)`
note: you could also interpret (4) as `DuplicateIndices`. I'm not sure what the correct interpretation is, but I went with `AttestingIndicesNotSorted` because it makes it so that duplicates only occur as …
> fix: sort/duplicate err for is_valid_indexed_attestation

- src/bin/README.md
- tests/README.md
minor fixes:
* add missing inline code delimiter for `gen-tests`
* change spec test instruction from `build-integration-tests` to `download-integration-tests`
> docs: minor fixes

- src/crypto.rs
> add `fmt::Debug` for `SecretKey`

- Cargo.toml
- rust-toolchain.toml
target stable versions to set the stage for removing `patch` attrs in downstream consumers
> update dep versions

- ethereum-consensus/src/altair/light_client.rs
add the following constants:
* `FINALIZED_ROOT_INDEX`
* `CURRENT_SYNC_COMMITTEE_INDEX`
* `NEXT_SYNC_COMMITTEE_INDEX`
add the following types:
* `LightClientHeader`
* `LightClientBootstrap`
* `LightClientFinalityUpdate`
* `LightClientOptimisticUpdate`
* `LightClientStore`
fixes:
* replace `BeaconBlockHeader` with `LightClientHeader` in `LightClientUpdate`
> feat: add missing altair types/constants

- ethereum-consensus/src/configs/goerli.rs
- ethereum-consensus/src/configs/holesky.rs
- ethereum-consensus/src/configs/mainnet.rs
- ethereum-consensus/src/configs/minimal.rs
- ethereum-consensus/src/configs/mod.rs
- ethereum-consensus/src/configs/sepolia.rs
- ethereum-consensus/src/networks.rs
- ethereum-consensus/src/state_transition/context.rs
> feat: add network type

- beacon-api-client/Cargo.toml
Hi, this allows not pulling the `hyper-tls` and its `openssl-sys` dependency and use `rustls` instead by downstream crates.
Thanks
> disable reqwest default-tls

- beacon-api-client/Cargo.toml
Only noticed after that `mev-rs` also depends on `beacon-api-client` which will also need to expose this option.
Thanks
> allow indirect sub crates to select tls flavor

- ethereum-consensus/src/capella/block_processing.rs
- ethereum-consensus/src/capella/bls_to_execution_change.rs
- ethereum-consensus/src/state_transition/error.rs
Took a stab at this and submitting a draft PR for feedback. 
This PR closes #249
> feat: implements process bls to execution change

- ethereum-consensus/src/bin/ec/validator/keystores.rs
- ethereum-consensus/src/bin/ec/validator/mod.rs
Fixes #270 
note: untested, but it should provide output sufficient for `lighthouse validator-manager import` which is a good target motivating #270
> produce output for `lighthouse validator-manager import`

- beacon-api-client/src/api_client.rs
- beacon-api-client/src/lib.rs
This refactor aims to simplify the api cilent interface by moving the 15 generics into a single `ClientTypes` marker trait.
This trait is then implemented for the two presets exported by the library.
Note: This is a breaking API change for users who defined their own beacon api clients.
(As suggested by @danipopes)
> refactor: use marker trait for client types

- ethereum-consensus/src/types/beacon_block.rs
- ethereum-consensus/src/types/beacon_state.rs
- ethereum-consensus/src/types/blinded_beacon_block.rs
- ethereum-consensus/src/types/execution_payload.rs
- ethereum-consensus/src/types/execution_payload_header.rs
- spec-gen/src/type_generator.rs
- spec-gen/src/visitors.rs
before, any generated accessor would always return a ref, even when the type is copy
now, we just return a copy to simplify the accessor set
> improvement to type-gen, if type is copy, just return directly

- beacon-api-client/src/api_client.rs
- beacon-api-client/src/lib.rs
in order to `Clone` the client, the inner type `C` declared in #287 must also be `Clone`
> ensure `beacon-api-client` "type group" is Clone

- ethereum-consensus/src/types/beacon_block.rs
- ethereum-consensus/src/types/beacon_block_body.rs
- ethereum-consensus/src/types/beacon_state.rs
- ethereum-consensus/src/types/blinded_beacon_block.rs
- ethereum-consensus/src/types/blinded_beacon_block_body.rs
- ethereum-consensus/src/types/execution_payload.rs
- ethereum-consensus/src/types/execution_payload_header.rs
- ethereum-consensus/src/types/signed_beacon_block.rs
- ethereum-consensus/src/types/signed_blinded_beacon_block.rs
- spec-gen/src/type_generator.rs
this caused hash tree root calculations to be incorrect, e.g. when verifying bids in https://github.com/ralexstokes/mev-rs
> missing `transparent` attr on generated types

- ethereum-consensus/src/networks.rs
only wrap the config directory, and then open the
expected file when loading the `Context`
this enables use here to get `config.yaml` for CL, or e.g. pass same `Network` in EL context to load `genesis.json`
> support use of `Network` in various contexts

- ethereum-consensus/src/deneb/blob_sidecar.rs
- ethereum-consensus/src/deneb/presets/mainnet.rs
- ethereum-consensus/src/deneb/presets/minimal.rs
- ethereum-consensus/src/deneb/spec/mod.rs
Fixes https://github.com/ralexstokes/ethereum-consensus/issues/306.
Note:  `kzg_commitment_inclusion_proof` is a vector of `Bytes32` in python spec.  
Do we want it to be an array?
`pub kzg_commitment_inclusion_proof = [Bytes32; KZG_COMMITMENT_INCLUSION_PROOF_DEPTH]`
> Update blob_sidecar type

- ethereum-consensus/src/clock.rs
The current holesky time stamp is wrong.
For example the timestamp of slot [308297](https://holesky.beaconcha.in/slot/308297) is 1699601964.
Using the correct genesis time we have 1695902400 + (308297 * 12) == 1699601964.
However, using the timestamp in the repo atm we have 1694786400 + (308297 * 12) == 1698485964.
> fix for HOLESKY_GENESIS_TIME

- beacon-api-client/Cargo.toml
Fix `rustls` feature by toggling `tls` features on `mev-share-sse` dependency.
Before:
```sh
➜ cargo tree -p beacon-api-client --no-default-features --features rustls --target all | grep openssl
│   │   │   │   ├── openssl v0.10.61
│   │   │   │   │   ├── openssl-macros v0.1.1 (proc-macro)
│   │   │   │   │   └── openssl-sys v0.9.97
│   │   │   │   ├── openssl-probe v0.1.5
│   │   │   │   ├── openssl-sys v0.9.97 (*)
```
After:
```sh
➜ cargo tree -p beacon-api-client --no-default-features --features rustls --target all | grep openssl
<no output>
```
> fix: `rustls` feature for beacon api client

- Cargo.toml
- beacon-api-client/Cargo.toml
- ethereum-consensus/Cargo.toml
- spec-gen/Cargo.toml
- test-gen/Cargo.toml
Fixes #325
i wasn't sure whether to add `dev-dependencies` to `[workspace.dependencies]`, so i didn't.
> Place crate dependencies in workspace dependencies

- spec-tests/main.rs
- spec-tests/runners/bls.rs
- spec-tests/runners/epoch_processing.rs
- spec-tests/runners/finality.rs
- spec-tests/runners/fork.rs
- spec-tests/runners/genesis.rs
- spec-tests/runners/mod.rs
- spec-tests/runners/operations.rs
- spec-tests/runners/random.rs
- spec-tests/runners/rewards.rs
- spec-tests/runners/sanity.rs
- spec-tests/runners/shuffling.rs
- spec-tests/runners/ssz_static.rs
- spec-tests/runners/transition.rs
- spec-tests/test_case.rs
- spec-tests/test_meta.rs
- spec-tests/test_utils.rs
simplify the macros from #335 so there is less code and hopefully is easier to extend in the future
todo
> refactor `spec-tests` macros

- Cargo.toml
- beacon-api-client/examples/get_block.rs
- beacon-api-client/src/types.rs
- ethereum-consensus/src/altair/block_processing.rs
- ethereum-consensus/src/bellatrix/spec/mod.rs
- ethereum-consensus/src/capella/spec/mod.rs
- ethereum-consensus/src/deneb/blob_sidecar.rs
- ethereum-consensus/src/deneb/spec/mod.rs
- ethereum-consensus/src/phase0/block_processing.rs
- ethereum-consensus/src/phase0/operations.rs
- ethereum-consensus/src/serde.rs
- ethereum-consensus/src/ssz/byte_list.rs
- ethereum-consensus/src/ssz/byte_vector.rs
- justfile
- spec-tests/runners/light_client.rs
- spec-tests/runners/ssz_static.rs
Main thing is updating the `ssz_rs::Node` type to use `alloy_primitives::B256`, and then removing or migrating some serialization code to simplify that crate.
> Update to latest version of `ssz-rs` with a variety of improvements

- ethereum-consensus/src/altair/block_processing.rs
- ethereum-consensus/src/bellatrix/spec/mod.rs
- ethereum-consensus/src/capella/spec/mod.rs
- ethereum-consensus/src/deneb/spec/mod.rs
- ethereum-consensus/src/phase0/block_processing.rs
simplifies how this constant is used to avoid interactions with visibility and the spec generation
> refactor `DEPOSIT_MERKLE_DEPTH` constant

- ethereum-consensus/src/altair/spec/mod.rs
- ethereum-consensus/src/bellatrix/spec/mod.rs
- ethereum-consensus/src/capella/spec/mod.rs
- ethereum-consensus/src/deneb/spec/mod.rs
- spec-gen/src/generator.rs
Fix #361 
Some types were blindly copied forward to each new `spec` module when they didn't need to be.
> Add better precision to what is generated by the spec-gen

- Cargo.toml
- ethereum-consensus/Cargo.toml
- ethereum-consensus/src/clock.rs
fix #215
to drop `async-stream` crate and requirement to `pin!`
> refactor `Clock::stream_slots`

- ethereum-consensus/src/altair/spec/mod.rs
- ethereum-consensus/src/bellatrix/spec/mod.rs
- ethereum-consensus/src/capella/block_processing.rs
- ethereum-consensus/src/capella/spec/mod.rs
- ethereum-consensus/src/deneb/spec/mod.rs
- ethereum-consensus/src/electra/spec/mod.rs
- ethereum-consensus/src/phase0/block_processing.rs
- ethereum-consensus/src/phase0/helpers.rs
- ethereum-consensus/src/signing.rs
this function exists to help with mutability issues that mandated by the previous `HashTreeRoot` impl that demanded a `mut&` to the data to sign over
now that this requirement has  been removed, we can get rid of this function
> drop unnecessary `verify_signature`

- ethereum-consensus/src/deneb/polynomial_commitments.rs
patching the cargo manifest to `v1.0.1` of `ethereum/c-kzg-4844` caused these build errors, and I am a little surprised why it was working in the first place actually..
> use correct conversion methods mapping `c-kzg` types to local types

- ethereum-consensus/src/electra/block_processing.rs
- ethereum-consensus/src/electra/execution_engine.rs
- ethereum-consensus/src/electra/execution_payload.rs
- ethereum-consensus/src/electra/helpers.rs
- ethereum-consensus/src/electra/mod.rs
- ethereum-consensus/src/electra/spec/mod.rs
- ethereum-consensus/src/error.rs
- spec-gen/src/generator.rs
#373
add block processing functions for the `electra` spec.
> feat: electra block processing
